name: Assignment Support Request
description: File a assignment support request
title: "[Assignment]: "
labels: ["assignment", "support"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request support on the assignments!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this assignment support request?
      description: Please search to see if an issue already exists for this.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: lab
    attributes:
      label: Lab
      description: What lab are you requesting support for?
      options:
        - Vector Add
        - Matrix Mult
        - DSPLib
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe which assignment you are requesting support for and what problems you are facing
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else that you would like to include?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false