name: Enhancement Request
description: File an issue for an enhancement request
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - mariodruiz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request an enhancement for these labs!
  - type: checkboxes
    attributes:
      label: Is there an existing issue related to your problem?
      description: Please search to see if an issue already exists for this.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: lab
    attributes:
      label: Lab
      description: What lab are you requesting an enhancement?
      options:
        - Vector Add 1
        - Vector Add 2
        - Matrix Mult
        - DSPLib
        - All of the above
    validations:
      required: true
  - type: textarea
    id: enh
    attributes:
      label: Description of the enhancement request
      description: |
        Please describe what enhancement you are requesting

      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else that you would like to include?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. If you are adding code, we suggest you use [code snippets](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
    validations:
      required: false